version: '2'
services:

        web:
            build: ./
            volumes:
                - ./:/var/www/html
                - ~/.composer/cache:/root/.composer/cache
                - ~/.ssh:/root/.ssh
                - ./services/php/local.ini:/user/local/etc/php/conf.d/local.ini
            links:
                - mysql
            expose:
                - 9000 

        nginx:
            build: ./services/nginx
            ports:
                - "999:443"
            links:
                - web
            volumes_from:
                - web

        mysql:
            image: "mysql:5.6"
            ports:
                - "3306:3306"
            volumes:
                - ./services/mysql:/etc/mysql/conf.d
            environment:
                - "MYSQL_ROOT_PASSWORD=root"
                - "MYSQL_DATABASE=onepiece"
            


