version: '2'
services:

        web:
            build: ./
            volumes:
                - ./:/var/www/html
                - ~/.composer/cache:/root/.composer/cache
                - ~/.ssh:/root/.ssh
                - ./services/php/local.ini:/user/local/etc/php/conf.d/local.ini
            links:
                - mysql
            expose:
                - 9000 

        nginx:
            build: ./services/nginx
            ports:
                - "881:443"
            links:
                - web
            volumes_from:
                - web

        mysql:
            image: mysql:5.6
            ports:
                - "3319:3306"
            expose:
                - "3306"
            environment:
              MYSQL_ROOT_PASSWORD: root
              MYSQL_DATABASE: web
              MYSQL_USER: web
              MYSQL_PASSWORD: web
            volumes:
                - ./services/mysql:/var/lib/mysql
                - ./services/mysql/mysql.cfg:/etc/mysql/conf.d/mysql.cfg



